### ISSUE TITLE
HiveConf of name hive.metastore.client.factory.class does not exist

### ISSUE THREAD

**Issue by dthauvin** [awslabs/aws-glue-data-catalog-client-for-apache-hive-metastore#26]
Hello 

I facing an issue , i always have this message warning and i am not able to use Aws Glue catalog as metastore for spark.

```bash
~/Documents/spark-2.4.4-bin-hadoop2.7/bin$ ./spark-shell
20/05/03 16:23:10 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
Spark context Web UI available at http://localhost:4040
Spark context available as 'sc' (master = local[*], app id = local-1588515796006).
Spark session available as 'spark'.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.4.4
      /_/

Using Scala version 2.11.12 (OpenJDK 64-Bit Server VM, Java 1.8.0_252)
Type in expressions to have them evaluated.
Type :help for more information.

scala> spark.sql("show databases").show()
20/05/03 16:23:28 WARN HiveConf: HiveConf of name hive.metastore.client.factory.class does not exist
20/05/03 16:23:29 WARN HiveConf: HiveConf of name hive.metastore.client.factory.class does not exist
+------------+
|databaseName|
+------------+
|     default|
+------------+

scala> spark.stop

scala> import org.apache.spark.sql.SparkSession
import org.apache.spark.sql.SparkSession

scala> val spark = SparkSession.builder().appName("Test_Glue_Catalog").config("spark.sql.catalogImplementation","hive").config("hive.metastore.connect.retries", 15).config("hive.metastore.client.factory.class","com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory").enableHiveSupport().getOrCreate();
spark: org.apache.spark.sql.SparkSession = org.apache.spark.sql.SparkSession@60e5b3a8

scala> val test = spark.sparkContext.getConf.getAll.foreach(println)
(spark.app.id,local-1588516420457)
(spark.sql.catalogImplementation,hive)
(spark.driver.port,56979)
(spark.jars,)
(hive.metastore.client.factory.class,com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory)
(spark.master,local[*])
(spark.executor.id,driver)
(spark.submit.deployMode,client)
(spark.driver.host,localhost)
(hive.metastore.connect.retries,15)
(spark.ui.showConsoleProgress,true)
(spark.app.name,Test_Glue_Catalog)
test: Unit = ()

scala> spark.sql("show databases").show()
20/05/03 16:33:59 WARN HiveConf: HiveConf of name hive.metastore.client.factory.class does not exist
20/05/03 16:34:01 WARN HiveConf: HiveConf of name hive.metastore.client.factory.class does not exist
+------------+
|databaseName|
+------------+
|     default|
+------------+
```

After building successfully the glue datacatalog `aws-glue-datacatalog-spark-client-1.10.0-SNAPSHOT.jar` , i follow step by step the readme.md : 

I put aws-glue-datacatalog-spark-client-1.10.0-SNAPSHOT.jar in `${SPARK_HOME}/jars/`
I configure my `hive-site.xml` under my `${SPARK_HOME}/conf/` with 

```xml
<configuration>
  <property>
    <name>hive.metastore.client.factory.class</name>
  <value>com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory</value>
  </property>
</configuration>
```
I try several configuration with `spark-2.4.4-bin-hadoop2.7` , `spark-2.4.5-bin-hadoop2.7` ,`spark-2.4.5-bin-without-hadoop` and `spark-3.0.0-preview2-bin-hadoop3.2`.

I don't understand why the client don't even try to connect on the Glue Endpoint . Spark will always use the default warehouse ...

i have no idea what's going on .

**Comment by rednaxelafx** [comment]
Hi @dthauvin ,

Your Spark distro needs to be customized with using a patched hive-exec.jar.

Assuming you've already done this part: You'd want to base off of some Hive 1.2.x version and apply the HIVE-12679 patch accordingly. https://github.com/awslabs/aws-glue-data-catalog-client-for-apache-hive-metastore#patching-apache-hive-and-installing-it-locally

Then your local Maven will be populated with the patched Hive JARs, and then you'll be able to make your own build of Spark based on that patched hive-exec.jar and allow Glue Catalog client to register properly.

If you use an out-of-the-box Spark binary distro, the hive-exec.jar included would be a vanilla unpatched version, and of course Glue client won't work.

**Comment by abhishtai** [comment]
I am facing similar issue, when submitted an application using spark-submit. 
Spark fails with following stack/cause:

> Caused by: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient
	at org.apache.hadoop.hive.metastore.MetaStoreUtils.newInstance(MetaStoreUtils.java:1523)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.<init>(RetryingMetaStoreClient.java:86)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:132)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:104)
	at org.apache.hadoop.hive.ql.metadata.Hive.createMetaStoreClient(Hive.java:3005)
	at org.apache.hadoop.hive.ql.metadata.Hive.getMSC(Hive.java:3024)
	at org.apache.hadoop.hive.ql.metadata.Hive.getAllDatabases(Hive.java:1234)

The spark distro has the patched hive-exec and the corresponding clinet jar which has the necessary AWSGlueDataCatalogHiveClientFactory class. And the jar is part of the CLASSPATH. 
The hive exec has the hardcoded value for the hive.metastore.client.factory.class in the hiveConf pointing to SessionHiveMetaStoreClient. And hence the value set to the  hive.metastore.client.factory.class in the hive config (hive-site.xml) does not seem to get picked.

**Comment by giorgioinf** [comment]
I had same issue with spark client one. I may not be the best option, but based on my tests, it worked for me.
I had to tweak the project because it doesn't compile.

Here the command log:

```console
$ git clone https://github.com/apache/hive.git
$ cd hive
hive$ git checkout branch-1.2
hive$ curl -OL https://issues.apache.org/jira/secure/attachment/12958417/HIVE-12679.branch-1.2.patch
hive$ patch -p0 <HIVE-12679.branch-1.2.patch
hive$ mvn clean install -DskipTests -Phadoop-2
```
The captured hive version is: `1.2.3-SNAPSHOT`

```console
hive$ cd ..
$ git clone https://github.com/awslabs/aws-glue-data-catalog-client-for-apache-hive-metastore.git
$ cd aws-glue-data-catalog-client-for-apache-hive-metastore
aws-glue-data-catalog-client-for-apache-hive-metastore$ sed -ri 's|<(spark-hive.version)>.+</(\1)>|<\1>1.2.3-SNAPSHOT</\1>|' pom.xml
aws-glue-data-catalog-client-for-apache-hive-metastore$ sed -i 's|org.spark-project.hive|org.apache.hive|' **/*/pom.xml
```
I had also to edit the `shims/spark-hive-shims/pom.xml`

```console
build/aws-glue-data-catalog-client-for-apache-hive-metastore$ vi shims/spark-hive-shims/pom.xml
```
Add at the end
```xml
        <dependency>
            <groupId>org.apache.hadoop</groupId>
            <artifactId>hadoop-common</artifactId>
            <version>${hadoop.version}</version>
            <scope>provided</scope>
        </dependency>
```
End finally compile the project without the hive2-client

```console
aws-glue-data-catalog-client-for-apache-hive-metastore$ mvn clean package -DskipTests -pl '!aws-glue-datacatalog-hive2-client'/
```

After that I followed the comment of @rednaxelafx replacing all hive jars inside of `$SPARK_HOME/jars`

```console
$ rm -f $SPARK_HOME/jars/hive-*.jar
$ mv -f aws-glue-data-catalog-client-for-apache-hive-metastore/aws-glue-datacatalog-spark-client/target/aws-glue-datacatalog-spark-client-*-SNAPSHOT.jar \
hive/beeline/target/hive-beeline-*-SNAPSHOT.jar \
hive/metastore/target/hive-metastore-*-SNAPSHOT.jar \
hive/jdbc/target/hive-jdbc-*-SNAPSHOT.jar \
hive/ql/target/hive-exec-*-SNAPSHOT.jar \
hive/cli/target/hive-cli-*-SNAPSHOT.jar \
$SPARK_HOME/jars/
```

Then just testing it.

My environment is a ec2 machine with AssumeRole permissions to access s3 and glue

I also noticed that catalogs without filled `location` they failed with `desc database <name>` command.

I hope it may help

**Comment by jasondavindev** [comment]
The correct property name is `hive.imetastoreclient.factory.class`
