### ISSUE TITLE
Spark 3.0 support

### ISSUE THREAD

**Issue by dszakallas** [awslabs/aws-glue-data-catalog-client-for-apache-hive-metastore#32]
Spark 3 uses the new DataSource API v2, with pluggable metastores. Do you plan to add support for it here or as a separate project? If I understand correctly, the new implementation can get rid of Hive completely.

**Comment by radcheb** [comment]
👍

**Comment by zlosim** [comment]
+1

**Comment by ruturaj04** [comment]
any update on when we can expect support for spark 3.x

**Comment by jystephan** [comment]
Hello - We're also interested in this, as some of our customers use this connector and are blocked with Spark 2.4. Do you have any updates to share? Feel free to reach out directly. Thanks!
Jean-Yves, Co-Founder @ Data Mechanics (https://www.datamechanics.co)

**Comment by ruturaj04** [comment]
For now we went with a manual route where we build hive 1.2.1 with the patch which enables glue catalog.

Used the above hive distribution to build the aws-glue-catalog client  for spark and used the same version of hive to build a distribution of spark 3.x 

This new spark 3.x distribution we build works like a charm with the aws-glue-spark-client 

For some reason could not get this to work with hive 2.x... (will put in some time later on to see if I can get it to work with hive 2.x )

**Comment by ismailsimsek** [comment]
managed to build with spark 3.x and 2.x [here](https://github.com/ismailsimsek/aws-glue-data-catalog-client-for-apache-hive-metastore)  
[spark release is here](https://github.com/ismailsimsek/aws-glue-data-catalog-client-for-apache-hive-metastore/releases/tag/hive2.3.9-SNAPSHOT_hadoop_3.2.0_aws_sdk_1.11.375_latest)

whole patching and building everything is not a good solution
it shouldn't be to much effort to develop spark catalog

**Comment by dszakallas** [comment]
For clarification, aws-glue-datacatalog-hive2-client is working with Spark 3.0 since the beginning, after a single modification, IRC bumping hive2 version to 2.3.7 and adding a missing method to one interface implementation which can be a stub.

This ticket is about having a Glue Catalog implementation for Spark WITHOUT Hive.

**Comment by jpugliesi** [comment]
For what it's worth, we've open sourced a fully contained build and docker image for Spark 3.1.1 (with the kubernetes deps), Hadoop 3.2.0, Hive 2.3.7, and this glue client:
https://github.com/viaduct-ai/docker-spark-k8s-aws

**Comment by rika** [comment]
> For what it's worth, we've open sourced a fully contained build and docker image for Spark 3.1.1 (with the kubernetes deps), Hadoop 3.2.0, Hive 2.3.7, and this glue client:
> https://github.com/viaduct-ai/docker-spark-k8s-aws

@jpugliesi I got your image running but I'm having some issues with *partitions* typed as *date* which i didn't have before with Spark 2.4.3.

When you have a partition with type `date` on a Glue table and you apply a filter for example:
```
spark.sql("select 1 from test.table where dt='2021-01-01' limit 1").count()
```
I'm getting:
```
org.apache.spark.sql.AnalysisException: org.apache.hadoop.hive.metastore.api.InvalidObjectException: Unsupported expression '2021 - 01 - 01' (Service: AWSGlue; Status Code: 400; Error Code: InvalidInputException; Request ID: 73ff7786-1a68-455f-bb0a-615c4eff8522; Proxy: null)
  at org.apache.spark.sql.hive.HiveExternalCatalog.withClient(HiveExternalCatalog.scala:112)
  at org.apache.spark.sql.hive.HiveExternalCatalog.listPartitionsByFilter(HiveExternalCatalog.scala:1264)
  at org.apache.spark.sql.catalyst.catalog.ExternalCatalogWithListener.listPartitionsByFilter(ExternalCatalogWithListener.scala:262)
  at org.apache.spark.sql.catalyst.catalog.SessionCatalog.listPartitionsByFilter(SessionCatalog.scala:1180)
  at org.apache.spark.sql.execution.datasources.CatalogFileIndex.filterPartitions(CatalogFileIndex.scala:74)
  at org.apache.spark.sql.execution.datasources.PruneFileSourcePartitions$$anonfun$apply$1.applyOrElse(PruneFileSourcePartitions.scala:98)
  at org.apache.spark.sql.execution.datasources.PruneFileSourcePartitions$$anonfun$apply$1.applyOrElse(PruneFileSourcePartitions.scala:78)
  at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDown$1(TreeNode.scala:317)
  at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:73)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:317)
  at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDown(LogicalPlan.scala:29)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDown(AnalysisHelper.scala:171)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDown$(AnalysisHelper.scala:169)
  at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDown(LogicalPlan.scala:29)
  at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDown(LogicalPlan.scala:29)
  at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDown$3(TreeNode.scala:322)
  at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$mapChildren$1(TreeNode.scala:407)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:243)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:405)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:358)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:322)
  at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDown(LogicalPlan.scala:29)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDown(AnalysisHelper.scala:171)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDown$(AnalysisHelper.scala:169)
  at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDown(LogicalPlan.scala:29)
  at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDown(LogicalPlan.scala:29)
  at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDown$3(TreeNode.scala:322)
  at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$mapChildren$1(TreeNode.scala:407)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:243)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:405)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:358)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:322)
  at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDown(LogicalPlan.scala:29)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDown(AnalysisHelper.scala:171)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDown$(AnalysisHelper.scala:169)
  at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDown(LogicalPlan.scala:29)
  at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDown(LogicalPlan.scala:29)
  at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDown$3(TreeNode.scala:322)
  at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$mapChildren$1(TreeNode.scala:407)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:243)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:405)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:358)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:322)
  at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDown(LogicalPlan.scala:29)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDown(AnalysisHelper.scala:171)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDown$(AnalysisHelper.scala:169)
  at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDown(LogicalPlan.scala:29)
  at org.apache.spark.sql.execution.datasources.PruneFileSourcePartitions$.apply(PruneFileSourcePartitions.scala:78)
  at org.apache.spark.sql.execution.datasources.PruneFileSourcePartitions$.apply(PruneFileSourcePartitions.scala:42)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$2(RuleExecutor.scala:216)
  at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
  at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
  at scala.collection.immutable.List.foldLeft(List.scala:89)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1(RuleExecutor.scala:213)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1$adapted(RuleExecutor.scala:205)
  at scala.collection.immutable.List.foreach(List.scala:392)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:205)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$executeAndTrack$1(RuleExecutor.scala:183)
  at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:88)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor.executeAndTrack(RuleExecutor.scala:183)
  at org.apache.spark.sql.execution.QueryExecution.$anonfun$optimizedPlan$1(QueryExecution.scala:87)
  at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
  at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:143)
  at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:772)
  at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:143)
  at org.apache.spark.sql.execution.QueryExecution.optimizedPlan$lzycompute(QueryExecution.scala:84)
  at org.apache.spark.sql.execution.QueryExecution.optimizedPlan(QueryExecution.scala:84)
  at org.apache.spark.sql.execution.QueryExecution.assertOptimized(QueryExecution.scala:95)
  at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:113)
  at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:110)
  at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:101)
  at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
  at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
  at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:772)
  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
  at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3685)
  at org.apache.spark.sql.Dataset.count(Dataset.scala:3005)
  ... 47 elided
Caused by: org.apache.hadoop.hive.metastore.api.InvalidObjectException: Unsupported expression '2021 - 01 - 01' (Service: AWSGlue; Status Code: 400; Error Code: InvalidInputException; Request ID: 73ff7786-1a68-455f-bb0a-615c4eff8522; Proxy: null)
  at com.amazonaws.glue.catalog.converters.CatalogToHiveConverter$5.get(CatalogToHiveConverter.java:58)
  at com.amazonaws.glue.catalog.converters.CatalogToHiveConverter.getHiveException(CatalogToHiveConverter.java:97)
  at com.amazonaws.glue.catalog.converters.CatalogToHiveConverter.wrapInHiveException(CatalogToHiveConverter.java:88)
  at com.amazonaws.glue.catalog.metastore.GlueMetastoreClientDelegate.getCatalogPartitions(GlueMetastoreClientDelegate.java:838)
  at com.amazonaws.glue.catalog.metastore.GlueMetastoreClientDelegate.getPartitions(GlueMetastoreClientDelegate.java:823)
  at com.amazonaws.glue.catalog.metastore.AWSCatalogMetastoreClient.listPartitionsByFilter(AWSCatalogMetastoreClient.java:1328)
  at org.apache.hadoop.hive.ql.metadata.Hive.getPartitionsByFilter(Hive.java:2682)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.apache.spark.sql.hive.client.Shim_v0_13.getPartitionsByFilter(HiveShim.scala:865)
  at org.apache.spark.sql.hive.client.HiveClientImpl.$anonfun$getPartitionsByFilter$1(HiveClientImpl.scala:749)
  at org.apache.spark.sql.hive.client.HiveClientImpl.$anonfun$withHiveState$1(HiveClientImpl.scala:291)
  at org.apache.spark.sql.hive.client.HiveClientImpl.liftedTree1$1(HiveClientImpl.scala:224)
  at org.apache.spark.sql.hive.client.HiveClientImpl.retryLocked(HiveClientImpl.scala:223)
  at org.apache.spark.sql.hive.client.HiveClientImpl.withHiveState(HiveClientImpl.scala:273)
  at org.apache.spark.sql.hive.client.HiveClientImpl.getPartitionsByFilter(HiveClientImpl.scala:747)
  at org.apache.spark.sql.hive.HiveExternalCatalog.$anonfun$listPartitionsByFilter$1(HiveExternalCatalog.scala:1273)
  at org.apache.spark.sql.hive.HiveExternalCatalog.withClient(HiveExternalCatalog.scala:102)
  ... 123 more
```

If I cast the partition column to string, it works fine, but I didn't have this problem even without casting on the previous version.
I know the Glue client is built on a [fork](https://github.com/viaduct-ai/aws-glue-data-catalog-client-for-apache-hive-metastore) from the AWS repo, not sure if some of the fork changes caused this.

**Comment by stijndehaes** [comment]
@rika See my issue here: https://github.com/awslabs/aws-glue-data-catalog-client-for-apache-hive-metastore/issues/45
Spark 3.1.x added partition pruning for date types (https://issues.apache.org/jira/browse/SPARK-33477). But this is unsupported by glue. EMR also fails on this

**Comment by codeslubber** [comment]
The market leader in cloud, dragging ass on all fronts. Thanks for nothing.. jesus we are using Scala 2.11 in our Glue project. It's the first piece I have done in Glue. Going to go find other ways to do my ETL that aren't victims of necrifying neglect.

**Comment by fnapolitano73** [comment]
Please refer to [branch 3.4](https://github.com/awslabs/aws-glue-data-catalog-client-for-apache-hive-metastore/tree/branch-3.4.0)

**Comment by ssilb4** [comment]
I had same error In emr 6.3.0 (Spark 3.1.1).
After upgrade to emr 6.5.0 (Spark 3.1.2), It solved.

**Comment by keerthivasan-r** [comment]
We are also getting the same exception while using float or double when using AWS Glue Catalog. I have tried multiple versions of EMR 6.8,6.5, 5,5 etc. I lack a deeper understanding of the glue catalog client. Can someone guide us in this regard?

But, we are able to see the table schema, partitions correctly in the Glue catalog tables.

An error was encountered:
```
org.apache.hadoop.hive.metastore.api.InvalidObjectException: Unknown type : 'double' (Service: AWSGlue; Status Code: 400; Error Code: InvalidInputException; Request ID: e34c5f24-1031-48f8-8694-5f7e84a56e66; Proxy: null)
Traceback (most recent call last):
  File "/mnt/yarn/usercache/livy/appcache/application_1668402519702_0003/container_1668402519702_0003_01_000001/pyspark.zip/pyspark/sql/dataframe.py", line 607, in show
    print(self._jdf.showString(n, 20, vertical))
  File "/mnt/yarn/usercache/livy/appcache/application_1668402519702_0003/container_1668402519702_0003_01_000001/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 1322, in __call__
    answer, self.gateway_client, self.target_id, [self.name](http://self.name/))
  File "/mnt/yarn/usercache/livy/appcache/application_1668402519702_0003/container_1668402519702_0003_01_000001/pyspark.zip/pyspark/sql/utils.py", line 196, in deco
    raise converted from None
pyspark.sql.utils.AnalysisException: org.apache.hadoop.hive.metastore.api.InvalidObjectException: Unknown type : 'double' (Service: AWSGlue; Status Code: 400; Error Code: InvalidInputException; Request ID: e34c5f24-1031-48f8-8694-5f7e84a56e66; Proxy: null)
```

**Comment by vfrank66** [comment]
We had this issue with int partitions, emr-6.11, it was difficult to track down the problem so i will post my solution here

```python
existing_df.filter(
                    ~(
                        (F.col("delivered_year") == 2020)
                        & (F.col("delivered_month") == 0)
                        & (F.col("delivered_day") == 0)
                    )
                ).show()
```

> Traceback (most recent call last):
>   File "<string>", line 2, in <module>
>   File "/opt/spark/python/pyspark/sql/dataframe.py", line 485, in show
>     print(self._jdf.showString(n, 20, vertical))
>   File "/opt/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1305, in __call__
>     answer, self.gateway_client, self.target_id, self.name)
>   File "/opt/spark/python/pyspark/sql/utils.py", line 117, in deco
>     raise converted from None
> pyspark.sql.utils.AnalysisException: org.apache.hadoop.hive.metastore.api.InvalidObjectException: Unknown operator '!=' (Service: AWSGlue; Status Code: 400; Error Code: InvalidInputException; Request ID: b9178544-ca98-4c5b-90dc-a2a63d74d58f; Proxy: null)

```python
existing_df.filter(
                    ~(
                        (F.col("delivered_year").cast("string") == str(2020))
                        & (F.col("delivered_month").cast("string") == string(01)
                        & (F.col("delivered_day").cast("string") == str(01))
                    )
                ).show()
```
