### ISSUE TITLE
Unfinished mock stubbing error when running test

### ISSUE THREAD

**Issue by MasterDDT** [awslabs/aws-glue-data-catalog-client-for-apache-hive-metastore#52]
I'm seeing the below error when running tests on master branch:

```
cd aws-glue-datacatalog-spark-client/
mvn test -Dmaven.javadoc.skip=true -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2
```

```
-------------------------------------------------------------------------------
Test set: com.amazonaws.glue.catalog.metastore.AWSCatalogMetastoreClientTest
-------------------------------------------------------------------------------
Tests run: 75, Failures: 0, Errors: 75, Skipped: 0, Time elapsed: 2.15 sec <<< FAILURE!
testGetFunctionInValidWithMetaException(com.amazonaws.glue.catalog.metastore.AWSCatalogMetastoreClientTest)  Time elapsed: 0.784 sec  <<<
org.mockito.exceptions.misusing.UnfinishedStubbingException:
Unfinished stubbing detected here:
-> at com.amazonaws.glue.catalog.metastore.AWSCatalogMetastoreClientTest.setUp(AWSCatalogMetastoreClientTest.java:160)

E.g. thenReturn() may be missing.
Examples of correct stubbing:
    when(mock.isOk()).thenReturn(true);
    when(mock.isOk()).thenThrow(exception);
    doThrow(exception).when(mock).someVoidMethod();
Hints:
 1. missing thenReturn()
 2. you are trying to stub a final method, you naughty developer!
 3: you are stubbing the behaviour of another mock inside before 'thenReturn' instruction if completed

        at com.amazonaws.glue.catalog.metastore.AWSCatalogMetastoreClientTest.setUp(AWSCatalogMetastoreClientTest.java:160)
```

**Comment by MasterDDT** [comment]
cc @vinayict @tushar-poddar-amazon

**Comment by MasterDDT** [comment]
I was able to fix it by changing `AWSCatalogMetastoreClientTest.setUp()` to this

```
    AWSGlueMetastore defStore = new DefaultAWSGlueMetastore(conf, glueClient);
    doReturn(defStore).when(metastoreFactory).newMetastore(conf);
```
